#!/bin/bash

function redirect {
	mkdir -p $(dirname x/$1)
	echo "<meta http-equiv=\"refresh\" content=\"0;URL='/$2'\" />" > "x/$1.html"
}

redirect \
	store/products/acrylic-powder-refill-fast-set \
	store/products/monomer-2oz-pouch-fast-set

redirect \
	store/products/acrylic-powder-refill-clean-acrylic \
	store/products/monomer-2oz-pouch-clean-acrylic
